# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name=b'alum')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name=b'artist')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name=b'date')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name=b'%Y-%m-%dT%H:%M:%S')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=50, verbose_name=b'course_id')),
                ('course_name', models.CharField(max_length=50, verbose_name=b'course_name')),
                ('course_begintime', models.CharField(max_length=50, verbose_name=b'course_begintime')),
                ('course_endtime', models.CharField(max_length=50, verbose_name=b'course_endtime')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=10, verbose_name=b'student_id')),
                ('student_name', models.CharField(max_length=50, verbose_name=b'student_name')),
                ('student_password', models.CharField(max_length=50, verbose_name=b'student_id')),
                ('student_grade', models.CharField(max_length=50, verbose_name=b'student_grade')),
                ('attendence', models.ManyToManyField(related_name='Attendence', through='app.Attendence', to='app.Course')),
                ('course1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstcourse', to='app.Course')),
                ('course2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondcourse', to='app.Course')),
            ],
        ),
        migrations.AddField(
            model_name='attendence',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='app.Course'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='app.Student'),
        ),
        migrations.AddField(
            model_name='alum',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Artist'),
        ),
    ]
