# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-14 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='ip',
            field=models.CharField(default=b'192.168.7.1', max_length=20, verbose_name=b'ip'),
        ),
    ]
