# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-14 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170314_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_semester',
            field=models.CharField(default=b'0', max_length=5, verbose_name=b'course_semester'),
        ),
    ]
