# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-14 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_course_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_begintime',
            field=models.DateTimeField(verbose_name=b'%H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_endtime',
            field=models.DateTimeField(verbose_name=b'%H:%M:%S'),
        ),
    ]
